# Generated by Django 5.1.3 on 2024-11-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='pessoa',
        ),
        migrations.AlterModelOptions(
            name='areas_saber',
            options={'verbose_name': 'Área do Saber', 'verbose_name_plural': 'Áreas do Saber'},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='frequencia',
            options={'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequências'},
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='ocupacao',
            options={'verbose_name': 'Ocupação', 'verbose_name_plural': 'Ocupações'},
        ),
        migrations.AlterModelOptions(
            name='tipo_avaliacao',
            options={'verbose_name': 'Tipo de Avaliação', 'verbose_name_plural': 'Tipos de Avaliação'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo_avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_avaliacao', verbose_name='Tipo de Avaliação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='area_saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas_saber', verbose_name='Área do Saber'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='area_saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas_saber', verbose_name='Área do Saber'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_inicio',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_previsao_termino',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Data Previsão de Término'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField(default='2000-01-01', verbose_name='Data')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
