# Generated by Django 5.1.3 on 2024-11-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_aluno_matricula_aluno_ra_frequencia_pessoa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='pessoa',
            new_name='aluno',
        ),
    ]
