# Generated by Django 5.1.3 on 2024-11-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pessoa_matricula_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(to='app.disciplina', verbose_name='Disciplinas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ocupacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação'),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='area_saber',
        ),
        migrations.AlterField(
            model_name='professor',
            name='ocupacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação'),
        ),
        migrations.AddField(
            model_name='curso',
            name='area_saber',
            field=models.ManyToManyField(to='app.areas_saber', verbose_name='Área do Saber'),
        ),
    ]
