# Generated by Django 5.1.3 on 2024-11-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_curso_disciplinas_alter_aluno_ocupacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='estudante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.aluno', verbose_name='Estudante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='estudantes',
            field=models.ManyToManyField(related_name='Disciplinas', through='app.Matricula', to='app.aluno', verbose_name='Estudantes'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='estudante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frequencias_estudante', to='app.aluno', verbose_name='Estudante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='app.disciplina', verbose_name='Disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, to='app.aluno', verbose_name='Alunos'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da avaliação', null=True, verbose_name='Descrição'),
        ),
    ]
